import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'ros2-intro',
        'nodes-topics-services',
        'rclpy-python-nodes',
        'urdf-links-joints',
        'launch-files',
        'mini-project',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Gazebo & Unity Simulation',
      items: [
        'gazebo-intro',
        'unity-robotics-simulation',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'nvidia-isaac-sim',
        'isaac-ros',
        'nav2',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Physical AI & Humanoid Robotics',
      items: [
        'module-4-vla/vla-intro',
        'module-4-vla/voice-to-action',
        'module-4-vla/cognitive-planning',
        'module-4-vla/humanoid-capstone',
      ],
    },
  ],
};

export default sidebars;
